// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/DjaPy/fot-twenty-readers-go/internal/kathismas/domain"
	"github.com/gofrs/uuid/v5"
)

// Ensure, that RepositoryReaderGroupMock does implement domain.RepositoryReaderGroup.
// If this is not the case, regenerate this file with moq.
var _ domain.RepositoryReaderGroup = &RepositoryReaderGroupMock{}

// RepositoryReaderGroupMock is a mock implementation of domain.RepositoryReaderGroup.
//
//	func TestSomethingThatUsesRepositoryReaderGroup(t *testing.T) {
//
//		// make and configure a mocked domain.RepositoryReaderGroup
//		mockedRepositoryReaderGroup := &RepositoryReaderGroupMock{
//			CreateFunc: func(ctx context.Context, group *domain.ReaderGroup) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id uuid.UUID) error {
//				panic("mock out the Delete method")
//			},
//			GetAllFunc: func(ctx context.Context) ([]domain.ReaderGroup, error) {
//				panic("mock out the GetAll method")
//			},
//			GetByIDFunc: func(ctx context.Context, id uuid.UUID) (*domain.ReaderGroup, error) {
//				panic("mock out the GetByID method")
//			},
//			UpdateFunc: func(ctx context.Context, group *domain.ReaderGroup) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedRepositoryReaderGroup in code that requires domain.RepositoryReaderGroup
//		// and then make assertions.
//
//	}
type RepositoryReaderGroupMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, group *domain.ReaderGroup) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id uuid.UUID) error

	// GetAllFunc mocks the GetAll method.
	GetAllFunc func(ctx context.Context) ([]domain.ReaderGroup, error)

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id uuid.UUID) (*domain.ReaderGroup, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, group *domain.ReaderGroup) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Group is the group argument value.
			Group *domain.ReaderGroup
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetAll holds details about calls to the GetAll method.
		GetAll []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Group is the group argument value.
			Group *domain.ReaderGroup
		}
	}
	lockCreate  sync.RWMutex
	lockDelete  sync.RWMutex
	lockGetAll  sync.RWMutex
	lockGetByID sync.RWMutex
	lockUpdate  sync.RWMutex
}

// Create calls CreateFunc.
func (mock *RepositoryReaderGroupMock) Create(ctx context.Context, group *domain.ReaderGroup) error {
	if mock.CreateFunc == nil {
		panic("RepositoryReaderGroupMock.CreateFunc: method is nil but RepositoryReaderGroup.Create was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Group *domain.ReaderGroup
	}{
		Ctx:   ctx,
		Group: group,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, group)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedRepositoryReaderGroup.CreateCalls())
func (mock *RepositoryReaderGroupMock) CreateCalls() []struct {
	Ctx   context.Context
	Group *domain.ReaderGroup
} {
	var calls []struct {
		Ctx   context.Context
		Group *domain.ReaderGroup
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *RepositoryReaderGroupMock) Delete(ctx context.Context, id uuid.UUID) error {
	if mock.DeleteFunc == nil {
		panic("RepositoryReaderGroupMock.DeleteFunc: method is nil but RepositoryReaderGroup.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedRepositoryReaderGroup.DeleteCalls())
func (mock *RepositoryReaderGroupMock) DeleteCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// GetAll calls GetAllFunc.
func (mock *RepositoryReaderGroupMock) GetAll(ctx context.Context) ([]domain.ReaderGroup, error) {
	if mock.GetAllFunc == nil {
		panic("RepositoryReaderGroupMock.GetAllFunc: method is nil but RepositoryReaderGroup.GetAll was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetAll.Lock()
	mock.calls.GetAll = append(mock.calls.GetAll, callInfo)
	mock.lockGetAll.Unlock()
	return mock.GetAllFunc(ctx)
}

// GetAllCalls gets all the calls that were made to GetAll.
// Check the length with:
//
//	len(mockedRepositoryReaderGroup.GetAllCalls())
func (mock *RepositoryReaderGroupMock) GetAllCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetAll.RLock()
	calls = mock.calls.GetAll
	mock.lockGetAll.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *RepositoryReaderGroupMock) GetByID(ctx context.Context, id uuid.UUID) (*domain.ReaderGroup, error) {
	if mock.GetByIDFunc == nil {
		panic("RepositoryReaderGroupMock.GetByIDFunc: method is nil but RepositoryReaderGroup.GetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedRepositoryReaderGroup.GetByIDCalls())
func (mock *RepositoryReaderGroupMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *RepositoryReaderGroupMock) Update(ctx context.Context, group *domain.ReaderGroup) error {
	if mock.UpdateFunc == nil {
		panic("RepositoryReaderGroupMock.UpdateFunc: method is nil but RepositoryReaderGroup.Update was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Group *domain.ReaderGroup
	}{
		Ctx:   ctx,
		Group: group,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, group)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedRepositoryReaderGroup.UpdateCalls())
func (mock *RepositoryReaderGroupMock) UpdateCalls() []struct {
	Ctx   context.Context
	Group *domain.ReaderGroup
} {
	var calls []struct {
		Ctx   context.Context
		Group *domain.ReaderGroup
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
